collision_monitor:
  ros__parameters:
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_nav"
    cmd_vel_out_topic: "collision/cmd_vel"
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.5
    source_timeout: 5.0
    base_shift_correction: true
    stop_pub_timeout: 2.0
    use_sim_time: true  # Added for Gazebo
    
    polygons: ["VelocityPolygonStop","PolygonStop"]
    
    PolygonStop:
      type: "polygon"
      points: "[0.3, 0.3, 0.3, -0.3, 0.0, -0.3, 0.0, 0.3]"
      action_type: "stop"
      min_points: 4
      visualize: True
      polygon_pub_topic: "polygon_stop"
      enabled: True
      
    VelocityPolygonStop:
      type: "velocity_polygon"
      action_type: "stop"
      min_points: 6
      visualize: true
      enabled: true
      polygon_pub_topic: "velocity_polygon_stop"
      velocity_polygons: ["stopped", "rotation", "translation_forward", "translation_backward"]
      holonomic: false
      
      # FIXED: Non-overlapping velocity ranges and double array points format
      
      stopped:
        points: [0.25, 0.25, 0.25, -0.25, -0.25, -0.25, -0.25, 0.25]
        linear_min: -0.01
        linear_max: 0.01
        theta_min: -0.1
        theta_max: 0.1
        
      rotation:
        points: [0.3, 0.3, 0.3, -0.3, -0.3, -0.3, -0.3, 0.3]
        linear_min: -0.01
        linear_max: 0.01
        theta_min: 0.1
        theta_max: 1.0
        
      translation_forward:
        points: [0.35, 0.3, 0.35, -0.3, -0.2, -0.3, -0.2, 0.3]
        linear_min: 0.01
        linear_max: 1.0
        theta_min: -1.0
        theta_max: 1.0
        
      translation_backward:
        points: [0.2, 0.3, 0.2, -0.3, -0.35, -0.3, -0.35, 0.3]
        linear_min: -1.0
        linear_max: -0.01
        theta_min: -1.0
        theta_max: 1.0
        
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "/scan"
      enabled: true
      source_timeout: 0.0  # Disable timeout for simulation
      
    pointcloud:
      type: "pointcloud"
      topic: "/intel_realsense_r200_depth/points"
      min_height: 0.1
      max_height: 0.5
      enabled: true
      source_timeout: 0.0  # Disable timeout for simulation
